= WildFly Jakarta EE TCK Runners
:toc:

This project runs the Jakarta EE TCK's. Details are listed below for the various TCK's.

== Configuration

For all TCK runners a server will be provisioned if the `JBOSS_HOME` environment variable is not set. If the environment
variable is set, that path will be used to run the TCK's.

== Running the TCK's

All TCK runners can be run individually unless explicitly stated below. To run a single TCK you can run:

[source,bash]
----
mvn clean verify -am -pl cdi-langmodel-tck,cdi-lite-tck
----

=== Running Against a Specific Build of WildFly

IMPORTANT: The build must container JAR's for modules. These are used for client side testing.

To run against a specific build of WildFly you must set the `JBOSS_HOME` environment variable to the path of the server.

[source,bash]
----
JBOSS_HOME=/path/to/wildfly mvn clean verify
----

This will run the TCK against that build of WildFly and will not provision a WildFly server.

=== Running a Single Test

Running a single test is fairly easy. You simply need to run:

[source,bash]
----
mvn clean verify -Dtest=SomeTests
----

In cases where the `maven-failsafe-plugin` is used, use the `-Dit.test=` property.

=== Jakarta EE Core Profile

To run the Jakarta EE Core Profile TCK you can use Maven with the `-Dcore.profile` system property.

[source,bash]
----
mvn clean verify -Dcore.profile
----

=== Debugging Tests

You can debug a test by using the WildFly Arquillian debug properties.

* `wildfly.debug`: enables debugging
* `wildfly.debug.port`: The port to listen on, defaults to 8787
* `wildfly.debug.suspend`: Waits for you to attach the debugger before the startup of WildFly continues

[source,bash]
----
mvn clean verify -Dtest=SomeTests -Dwildfly.debug -Dwildfly.debug.port=5005 -Dwildfly.debug.suspend
----

== Testing Properties

The following is a table of properties that can be used when running the various TCK's.

|===
|Property |Definition

|`core.profile`
|Runs the required TCK's for the Jakarta EE Core Profile
|===
