= WildFly Notes

To test a specific version of WildFly you must set the `JBOSS_HOME` environment variable. If the JBOSS_HOME` environment
variable is not set a default server will be provisioned.

You can also override the version of the provisioned server by passing the `version.org.wildfly` system property with
the version you'd like to test.

IMPORTANT: The WildFly container being tested must not be a Maven Distribution with no JAR's. The JAR's are expected
for signature tests.

== Standalone TCKs

In order to run the standalone TCK's on their own, you must run the `tck-setup` project first. This installs the
required TCK dependencies into your defined Maven repository.

The simplest way to run all the tests is to run:

[source,bash]
----
mvn clean verify
----

To run against a local install of WildFly:

[source,bash]
----
JBOSS_HOME="/opt/servers/custom-wildfly" mvn clean verify
----

To provision with a specific version of WildFly:

[source,bash]
----
mvn clean verify -Dversion.org.wildfly=27.0.0.Final
----

To provision a custom version of WildFly:

[source,bash]
----
mvn clean verify -Dfeature.pack.groupId=org.wildfly -Dfeature.pack.artifactId=wildfly-ee-galleon-pack -Dfeature.pack.version=27.0.0.Final
----

=== JSON-P TCK

cd to the jsonp-standalone-tck directory and run:

. `mvn verify`

=== JSON-B TCK

cd to the jsonb-standalone-tck directory and run:

. `mvn verify`

=== REST TCK
cd to the rest-tck directory and run:

. `mvn verify`


=== Dependency Injection TCK
cd to the inject-tck directory and run:

. `mvn verify`

=== CDI TCK
cd to the cdi-tck directory and run:

. `mvn verify`

=== CDI Lang Model TCK
cd to the cdi-langmodel-tck directory and run:

. `mvn test`

=== Core Profile TCK

cd to the core-tck directory and run:

. `mvn verify`

== Bleeding Edge

If you are developing the Core Profile TCK, then you will rely on snapshot builds of:

* https://github.com/eclipse-ee4j/jakartaee-tck/tree/master (core-profile-tck subfolder)  - The Jakarta Core Profile TCK
* https://github.com/wildfly/wildfly.git - wildfly with latest EE10 changes. Use the wildfly/dist/target/wildfly-x.y.z.q-SNAPSHOT local build root as your JBOSS_HOME directory
