== WildFly Preview Notes
A snapshot build of the current https://github.com/wildfly/wildfly.git ee-9 contents are required.

This is a trimmed down version of the Weld jboss-tck-runner that focuses on just running the standalone TCK required for the Jakarta EE 10 Core Profile, along with the Jakarta Core Profile TCK integration tests.

This current relies on snapshot builds of:
* https://github.com/jakartaredhat/core-profile-tck.git - The Jakarta Core Profile TCK candidate repo
* https://github.com/wildfly/wildfly.git - wildfly with latest EE10 changes

=== Quickstart

1. Build the local repositories needed for snapshots
1. Make sure your JBOSS_HOME env var points to wildfly repo export wildfly/ee-9/dist/target/wildfly-preview-27.0.0.Beta1-SNAPSHOT local build
1. Run `mvn -Pstaging -Pupdate-wildfly package` to install the CDI TCK extras
1. Run standalone TCKs
** `mvn -Pstaging -Dtarget=jsonp-tck verify`
** `mvn -Pstaging -Dtarget=jsonp-tck-standalone verify`
** `mvn -Pstaging -Dtarget=cdi-tck verify`
** `mvn -Pstaging -Dtarget=rest-tck verify`
1. Run the core profile TCK
** `mvn -Pstaging -Dtarget=core-tck verify`
